### ISSUE TITLE
add in a tab that shows the network visualisation

### ISSUE THREAD

**Issue by j-ong** [zubirsaid/zubirsaid#12]
explore using Cytoscape to visualise the api data
https://betterprogramming.pub/interactive-data-graphing-in-react-95d7963247ff
https://js.cytoscape.org/#getting-started/including-cytoscape.js

**Comment by KelvinHew** [comment]
Basic node - edges display implemented.

**Comment by j-ong** [comment]
Can link pull request in the future 
![Screenshot 2021-09-15 at 11 47 54 PM](https://user-images.githubusercontent.com/49931213/133466195-0bdf8e63-f7e0-4e55-a099-0009ab770eb4.png)
