### ISSUE TITLE
Dashboard - Purple box - Reflect counter of content

### ISSUE THREAD

**Issue by j-ong** [zubirsaid/zubirsaid#42]
Show counters related to genre and songs.

9 
Total Songs

x
Articles

x
Film

![Screenshot 2021-09-15 at 11 33 47 PM](https://user-images.githubusercontent.com/49931213/133463893-8e518027-f6e4-4a46-acb7-3fd469e02d67.png)

Developer to check against the data inside each genre to pick relevant genre to show.

What it should not show
- Do not show data that is not in the database i.e. composition period and music label. (has been removed)

**Comment by Han555** [comment]
Implemented the suggested changes in today's merge to main branch from feature dashboard branch. Thus am closing this issue.

**Comment by Han555** [comment]
Implemented the suggested changes in today's merge to main branch from feature dashboard branch. Thus am closing this issue.
