### ISSUE TITLE
Dashboard - Works of Zubir Said

### ISSUE THREAD

**Issue by j-ong** [zubirsaid/zubirsaid#43]
Developer can decide if we are showing videos or a list of songs that he has written.

If doing video playlist
- Can remove the song list link if it is not relevant
- Change the title to 'Videos of Zubir Said' if we are showing videos
- The videos have to be from the database https://zubirsaid.netlify.app/node/VideoFile
- Use a video player to allow user to toggle between the videos available

If doing song playlist
- List the songs in the database
- Link each song name to the nodes page
- (Unable to embed song player here as the database doesn't contain the music files)

**Comment by Han555** [comment]
Implemented the suggested changes in today's merge to main branch from feature dashboard branch. Thus am closing this issue.
